/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package handenur_agbulut_20070006069;

import javax.swing.JOptionPane;

/**
 *
 * @author Handenur
 */
public class Login_Page extends javax.swing.JFrame {

    /**
     * Creates new form Login_Page
     */
    public Login_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        loginbuton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 117, 42));
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 217, 45));

        loginbuton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        loginbuton.setText("LOGIN");
        loginbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbutonActionPerformed(evt);
            }
        });
        jPanel2.add(loginbuton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 160, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 609));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbutonActionPerformed
        
        String user = username.getText();
        
        
        if(user.equals("hande"))
        {
            JOptionPane.showMessageDialog(this,"succesful " + " welcome "+ user,"INFORMATION_MESSAGE",JOptionPane.INFORMATION_MESSAGE);  
            CreatMovie movie = new CreatMovie();
            movie.setVisible(true); 
            this.setVisible(false);
        }
        else if(user.equals("nilay"))
        {
            JOptionPane.showMessageDialog(this,"succesful " + " welcome "+ user,"INFORMATION_MESSAGE",JOptionPane.INFORMATION_MESSAGE);  
            CreatMovie movie = new CreatMovie();
            movie.setVisible(true); 
            this.setVisible(false);
        }
        else if(user.equals("dilara"))
        {
            JOptionPane.showMessageDialog(this,"Successful " + " welcome "+ user,"INFORMATION_MESSAGE",JOptionPane.INFORMATION_MESSAGE);  
            CreatMovie movie = new CreatMovie();
            movie.setVisible(true); 
            this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Your username is incorrect, Please! try again","ERROR",JOptionPane.ERROR_MESSAGE);  
        } 
        
    }//GEN-LAST:event_loginbutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginbuton;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
