package handenur_agbulut_20070006069;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Handenur
 */
public class MoviePosters extends javax.swing.JFrame {

    /**
     * Creates new form MoviePosters
     */
    public MoviePosters() {
        initComponents();
        
    }
    public void my_update(String str)
    {
        
        if(str.equals("1"))
        {
//            poster_1.enable(true);
            
            poster_1.setVisible(true);
            poster_2.setVisible(false);
            poster_3.setVisible(false);
            poster_4.setVisible(false);
            poster_5.setVisible(false);
            jLabel1.setVisible(true);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            
        }
        else if(str.equals("2"))
        {
           
            poster_1.setVisible(false);
            poster_2.setVisible(true);
            poster_3.setVisible(false);
            poster_4.setVisible(false);
            poster_5.setVisible(false);   
            jLabel1.setVisible(false);
            jLabel3.setVisible(true);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
        }
        else if(str.equals("3"))
        {
//            poster_1.enable(true);
            
            poster_1.setVisible(false);
            poster_2.setVisible(false);
            poster_3.setVisible(true);
            poster_4.setVisible(false);
            poster_5.setVisible(false);
            jLabel1.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(true);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
        }
        else if(str.equals("4"))
        {
//            poster_1.enable(true);
            
            poster_1.setVisible(false);
            poster_2.setVisible(false);
            poster_3.setVisible(false);
            poster_4.setVisible(true);
            poster_5.setVisible(false);
            jLabel1.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(true);
            jLabel6.setVisible(false);
        }
        else if(str.equals("5"))
        {
//            poster_1.enable(true);
            
            poster_1.setVisible(false);
            poster_2.setVisible(false);
            poster_3.setVisible(false);
            poster_4.setVisible(false);
            poster_5.setVisible(true);
            jLabel1.setVisible(true);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(true);
        }
        else
        {
                JOptionPane.showMessageDialog(this, "Please! try again" ,"Error message",JOptionPane.INFORMATION_MESSAGE);
                poster_1.setVisible(false);
                poster_2.setVisible(false);
                poster_3.setVisible(false);
                poster_4.setVisible(false);
                poster_5.setVisible(false);
                jLabel1.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jLabel5.setVisible(false);
                jLabel6.setVisible(false);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        poster_1 = new javax.swing.JButton();
        poster_2 = new javax.swing.JButton();
        poster_3 = new javax.swing.JButton();
        poster_4 = new javax.swing.JButton();
        poster_5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        go = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        poster_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/captainMarvel.jpg"))); // NOI18N
        poster_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(poster_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, 380));

        poster_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aladdin.png"))); // NOI18N
        getContentPane().add(poster_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 250, 360));

        poster_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/la_la_land.jpg"))); // NOI18N
        getContentPane().add(poster_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 250, 350));

        poster_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/batman.jpg"))); // NOI18N
        getContentPane().add(poster_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 260, 360));

        poster_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/the_conservation_game.jpg"))); // NOI18N
        getContentPane().add(poster_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 250, 360));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Captain Marvel");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 180, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Aladdin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("La La Land");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Batman");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("The Conservation Game");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, -1));

        back.setText("Back to movie id page");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 220, 70));

        go.setText("Go to show movie star");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        getContentPane().add(go, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 230, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        MovieIdPage ıd= new MovieIdPage();
        ıd.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_backActionPerformed

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        Show_movies_star show = new Show_movies_star();
        show.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_goActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoviePosters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoviePosters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoviePosters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoviePosters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoviePosters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton go;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton poster_1;
    private javax.swing.JButton poster_2;
    private javax.swing.JButton poster_3;
    private javax.swing.JButton poster_4;
    private javax.swing.JButton poster_5;
    // End of variables declaration//GEN-END:variables
}
