/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package handenur_agbulut_20070006069;

import java.awt.ComponentOrientation;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Handenur
 */
public class MoviesList extends javax.swing.JFrame {
public static void getMovieList()
    {
        File f = new File("src//Movie.txt");
        try
        {
            BufferedReader reader = new BufferedReader(new FileReader(f)); 
            String line = null;
            while ((line =reader.readLine())!= null)
            {
                movielisttextarea.append(line);
                
            }
        } catch (IOException ex) {
        Logger.getLogger(MoviesList.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    /**
     * Creates new form ShowMoviesList
     */
    public MoviesList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BackCreateMoviePage = new javax.swing.JButton();
        GoToStarpage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        movielisttextarea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Movie List");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 57, 401, -1));

        BackCreateMoviePage.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        BackCreateMoviePage.setText("Back Create Movie Page");
        BackCreateMoviePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackCreateMoviePageActionPerformed(evt);
            }
        });
        getContentPane().add(BackCreateMoviePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 527, -1, 50));

        GoToStarpage.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        GoToStarpage.setText("Go to Star Page");
        GoToStarpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToStarpageActionPerformed(evt);
            }
        });
        getContentPane().add(GoToStarpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 240, 50));

        movielisttextarea.setEditable(false);
        movielisttextarea.setBackground(new java.awt.Color(255, 255, 255));
        movielisttextarea.setColumns(20);
        movielisttextarea.setLineWrap(true);
        movielisttextarea.setRows(5);
        jScrollPane1.setViewportView(movielisttextarea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 650, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/4.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoToStarpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToStarpageActionPerformed

        Stars_Page star = new Stars_Page();
        star.setVisible(true); 
        this.setVisible(false); 
        
    }//GEN-LAST:event_GoToStarpageActionPerformed

    private void BackCreateMoviePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackCreateMoviePageActionPerformed
        CreatMovie movie = new CreatMovie();
        movie.setVisible(true); 
        this.setVisible(false); 
        MoviesList.getMovieList();
    }//GEN-LAST:event_BackCreateMoviePageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoviesList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoviesList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoviesList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoviesList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoviesList().setVisible(true);
                MoviesList.getMovieList();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackCreateMoviePage;
    private javax.swing.JButton GoToStarpage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea movielisttextarea;
    // End of variables declaration//GEN-END:variables
}
