/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package handenur_agbulut_20070006069;


import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Handenur
 */
public class Stars_Page extends javax.swing.JFrame {
    /**
     * Creates new form Star_Page
     */
    public Stars_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        showStarList = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        namesurname = new javax.swing.JTextField();
        movietitle = new javax.swing.JTextField();
        movieyear = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Movie Title:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Movie Year:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name Surname:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 210, 50));

        showStarList.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        showStarList.setForeground(new java.awt.Color(51, 255, 0));
        showStarList.setText("Show Stars List");
        showStarList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStarListActionPerformed(evt);
            }
        });
        getContentPane().add(showStarList, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 280, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Stars Page");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 360, -1));
        getContentPane().add(namesurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 310, 40));
        getContentPane().add(movietitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 310, 40));
        getContentPane().add(movieyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 310, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
//        int movieid = 1;
//        movieid = movieid ++;//movieid artsın kendi kendine 
        String title = movietitle.getText();
        String year = movieyear.getText();
        String names = namesurname.getText();
           
           File f = new File("src//Stars.txt");
        try {
//          BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(f)));
            BufferedWriter writer = new BufferedWriter(new FileWriter(f,true));
            Stars m = new Stars();
            writer.append(m.getId()+" "+title + " "+ year + " " + names + "\n");
            writer.close();
            JOptionPane.showMessageDialog(null, "Success");
            setVisible(false);
            new Stars_Page().setVisible(true);
        }
        catch (FileNotFoundException ex) {
            
        } catch (IOException ex) {
            Logger.getLogger(CreatMovie.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(f))); 
            String s = reader.readLine();
            
        } catch (FileNotFoundException ex) {
            
        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showStarListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStarListActionPerformed
        
        StarsList star = new StarsList();
        star.setVisible(true); 
        this.setVisible(false); 
        StarsList.getStarsList();
        
    }//GEN-LAST:event_showStarListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stars_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stars_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stars_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stars_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stars_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField movietitle;
    private javax.swing.JTextField movieyear;
    private javax.swing.JTextField namesurname;
    private javax.swing.JButton showStarList;
    // End of variables declaration//GEN-END:variables
}
