/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package handenur_agbulut_20070006069;

import java.awt.ComponentOrientation;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Handenur
 */
public class StarsList extends javax.swing.JFrame {
public static void getStarsList()
    {
        File f = new File("src//Stars.txt");
        try
        {
            BufferedReader reader = new BufferedReader(new FileReader(f)); 
            String line = null;
            while ((line =reader.readLine())!= null)
            {
               starlisttextarea.append(line);
                
                
            }
        } catch (IOException ex) {
        Logger.getLogger(MoviesList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * Creates new form StarsList
     */
    public StarsList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BackStarsPage = new javax.swing.JButton();
        GoToMovieIdPage = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        starlisttextarea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Stars List");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 275, 65));

        BackStarsPage.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        BackStarsPage.setText("Back Stars Page");
        BackStarsPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackStarsPageActionPerformed(evt);
            }
        });
        getContentPane().add(BackStarsPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 310, 50));

        GoToMovieIdPage.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        GoToMovieIdPage.setText("Go to Movie Id Page");
        GoToMovieIdPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToMovieIdPageActionPerformed(evt);
            }
        });
        getContentPane().add(GoToMovieIdPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 270, 50));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        starlisttextarea.setEditable(false);
        starlisttextarea.setBackground(new java.awt.Color(255, 255, 255));
        starlisttextarea.setColumns(20);
        starlisttextarea.setForeground(new java.awt.Color(255, 255, 255));
        starlisttextarea.setLineWrap(true);
        starlisttextarea.setRows(5);
        starlisttextarea.setToolTipText("");
        jScrollPane2.setViewportView(starlisttextarea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 620, 280));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/4.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackStarsPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackStarsPageActionPerformed
        Stars_Page star = new Stars_Page();
        star.setVisible(true); 
        this.setVisible(false); 
        StarsList.getStarsList();
    }//GEN-LAST:event_BackStarsPageActionPerformed

    private void GoToMovieIdPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToMovieIdPageActionPerformed
        MovieIdPage ıd= new MovieIdPage();
        ıd.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_GoToMovieIdPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StarsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StarsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StarsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StarsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StarsList().setVisible(true);
                StarsList.getStarsList();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackStarsPage;
    private javax.swing.JButton GoToMovieIdPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTextArea starlisttextarea;
    // End of variables declaration//GEN-END:variables
}
